#include "GridGlobalDelegates.h"

FOnAvtiveInputModeChanged FGridGlobalDelegates::OnActiveInputModeChanged;
FOnChessPieceTurnOver FGridGlobalDelegates::OnChessPieceTurnOver;
FOnChessPieceSelectChanged FGridGlobalDelegates::OnChessPieceSelectChanged;
FOnChessPieceActionOver FGridGlobalDelegates::OnChessPieceActionOver;
FOnGridNewCardAdded FGridGlobalDelegates::OnGridNewCardAdded;
FSimpleMulticastDelegate FGridGlobalDelegates::OnRemoveVisibleRangeDisplay;