#include "GridGlobalDelegates.h"

FOnAvtiveInputModeChanged FGridGlobalDelegates::OnActiveInputModeChanged;
FOnChessPieceTurnOver FGridGlobalDelegates::OnChessPieceTurnOver;
FOnChessPieceSelectChanged FGridGlobalDelegates::OnChessPieceSelectChanged;
